namespace ERPsystem.Domain.Enums.Finance
{
    /// <summary>نوع القيد اليومي</summary>
    public enum JournalEntryType 
    { 
        AutoGenerated, 
        Manual, 
        Recurring, 
        Opening, 
        Closing, 
        Reversal 
    }
}
